- hosts: localhost
  tasks:
    - openstack.cloud.server:
        state: present
        cloud: my_cloud
        name: vm-ansible-test
        image: <IMAGEID>
        key_name: <KEYPAIRS>
        timeout: 200
        flavor: m1.medium
        security_groups: default
        auto_ip: yes
